Metrics/LineLength:
  Max: 92

Documentation:
  Enabled: false

Style/Documentation:
  Include:
    - app/models/**
    - lib/**/*

AllCops:
    Exclude:
      - db/**/*
      - config/initializers/**/*
      - config/environments/**/*
      - config/application.rb
      - app/models/ckeditor/**/*
      - app/uploaders/**/*
      - Gemfile
      - Rakefile
