language: ruby

cache: bundler

before_install:
  - gem update --system
  - gem --version
  - gem install bundler --no-rdoc --no-ri
  - bundle --version

install: bundle install

script:
  rails test
  rubocop

rvm:
  - 2.5.3
