language: ruby

cache: bundler

jobs:
  include:
    - stage: prepare cache
      script: true
      rvm: 2.5.3

before_install:
  - gem update --system
  - gem --version
  - gem install bundler --no-rdoc --no-ri
  - bundle --version

install: bundle install

script:
  - bundle exec rake test
  - bundle exec rubocop

rvm:
  - 2.5.3
